"""Initial migration - Create all tables

Revision ID: 001_initial
Revises: 
Create Date: 2026-04-09 18:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Create companies table
    op.create_table(
        'companies',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('ruc_encrypted', sa.LargeBinary, nullable=False),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('razon_social', sa.String(255), nullable=False),
        sa.Column('contact_email', sa.String(255), nullable=True),
        sa.Column('contact_name', sa.String(255), nullable=True),
        sa.Column('contact_phone', sa.String(50), nullable=True),
        sa.Column('plan_tier', sa.Enum('free', 'basic', 'gold', 'founder', name='plantier'), default='free'),
        sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='companystatus'), default='active'),
        sa.Column('is_founder', sa.Boolean, default=False),
        sa.Column('founder_expires_at', sa.DateTime, nullable=True),
        sa.Column('max_monthly_queries', sa.Integer, default=100),
        sa.Column('contractual_obligation', sa.Boolean, default=False),
        sa.Column('contractual_signed_at', sa.DateTime, nullable=True),
        sa.Column('retained_until', sa.DateTime, nullable=True),
        sa.Column('invite_depth', sa.Integer, default=0),
        sa.Column('invited_by_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('password_hash', sa.String(255), nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create founder_applications table
    op.create_table(
        'founder_applications',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('ruc_encrypted', sa.LargeBinary, nullable=True),
        sa.Column('company_name', sa.String(255), nullable=False),
        sa.Column('contact_name', sa.String(255), nullable=False),
        sa.Column('contact_email', sa.String(255), nullable=False),
        sa.Column('contact_phone', sa.String(50), nullable=True),
        sa.Column('annual_volume', sa.String(50), nullable=False),
        sa.Column('subcontractor_count', sa.String(50), nullable=False),
        sa.Column('status', sa.Enum('pending', 'under_review', 'approved', 'rejected', 'waitlisted', name='applicationstatus'), default='pending'),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('reviewed_by', sa.String(255), nullable=True),
        sa.Column('reviewed_at', sa.DateTime, nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create invites table
    op.create_table(
        'invites',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('invite_code', sa.String(12), unique=True, nullable=False, index=True),
        sa.Column('inviter_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('inviter_company_name', sa.String(255), nullable=False),
        sa.Column('invitee_email', sa.String(255), nullable=False),
        sa.Column('invitee_company_name', sa.String(255), nullable=True),
        sa.Column('invitee_ruc_hash', sa.String(64), nullable=True),
        sa.Column('expected_plan', sa.String(50), nullable=True),
        sa.Column('monthly_value', sa.Numeric(12, 2), nullable=True),
        sa.Column('depth_level', sa.Integer, default=1),
        sa.Column('parent_invite_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.Enum('sent', 'opened', 'clicked', 'registered', 'expired', name='invitestatus'), default='sent'),
        sa.Column('email_sent_at', sa.DateTime, nullable=True),
        sa.Column('email_opened_at', sa.DateTime, nullable=True),
        sa.Column('link_clicked_at', sa.DateTime, nullable=True),
        sa.Column('registered_at', sa.DateTime, nullable=True),
        sa.Column('expires_at', sa.DateTime, nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create public_profiles table
    op.create_table(
        'public_profiles',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False, unique=True),
        sa.Column('slug', sa.String(100), unique=True, nullable=False, index=True),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('company_name', sa.String(255), nullable=False),
        sa.Column('score', sa.Integer, nullable=True),
        sa.Column('risk_level', sa.String(20), nullable=True),
        sa.Column('sello_status', sa.Enum('gold', 'silver', 'bronze', 'expired', 'none', name='sellostatus'), default='none'),
        sa.Column('verifications_count', sa.Integer, default=0),
        sa.Column('valid_until', sa.DateTime, nullable=True),
        sa.Column('is_public', sa.Boolean, default=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create verification_requests table
    op.create_table(
        'verification_requests',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='verificationstatus'), default='pending'),
        sa.Column('data_sources', postgresql.JSONB, default=list),
        sa.Column('results', postgresql.JSONB, nullable=True),
        sa.Column('score', sa.Integer, nullable=True),
        sa.Column('risk_level', sa.String(20), nullable=True),
        sa.Column('processing_started_at', sa.DateTime, nullable=True),
        sa.Column('completed_at', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create comparisons table
    op.create_table(
        'comparisons',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('ruc_hashes', postgresql.JSONB, nullable=False),
        sa.Column('results', postgresql.JSONB, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create compliance_checks table
    op.create_table(
        'compliance_checks',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('check_type', sa.String(50), nullable=False),
        sa.Column('status', sa.Enum('pending', 'passed', 'failed', 'warning', name='compliancestatus'), default='pending'),
        sa.Column('details', postgresql.JSONB, nullable=True),
        sa.Column('checked_at', sa.DateTime, nullable=True),
        sa.Column('expires_at', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    
    # Create digital_signatures table
    op.create_table(
        'digital_signatures',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('verification_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('signature_id', sa.String(255), unique=True, nullable=False),
        sa.Column('document_hash', sa.String(64), nullable=False),
        sa.Column('certificate_id', sa.String(255), nullable=True),
        sa.Column('signed_at', sa.DateTime, nullable=False),
        sa.Column('expires_at', sa.DateTime, nullable=False),
        sa.Column('pdf_url', sa.String(500), nullable=True),
        sa.Column('is_valid', sa.Boolean, default=True),
        sa.Column('revoked_at', sa.DateTime, nullable=True),
        sa.Column('revocation_reason', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
    )
    
    # Create api_keys table
    op.create_table(
        'api_keys',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('key_hash', sa.String(64), unique=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=True),
        sa.Column('scopes', postgresql.JSONB, default=list),
        sa.Column('rate_limit', sa.Integer, default=1000),
        sa.Column('last_used_at', sa.DateTime, nullable=True),
        sa.Column('expires_at', sa.DateTime, nullable=True),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create webhooks table
    op.create_table(
        'webhooks',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('url', sa.String(500), nullable=False),
        sa.Column('events', postgresql.JSONB, nullable=False),
        sa.Column('secret', sa.String(255), nullable=True),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create webhook_deliveries table
    op.create_table(
        'webhook_deliveries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('webhook_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event', sa.String(100), nullable=False),
        sa.Column('payload', postgresql.JSONB, nullable=False),
        sa.Column('response_status', sa.Integer, nullable=True),
        sa.Column('response_body', sa.Text, nullable=True),
        sa.Column('attempt_count', sa.Integer, default=1),
        sa.Column('delivered_at', sa.DateTime, nullable=True),
        sa.Column('next_retry_at', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
    )
    
    # Create sanctions_cache table
    op.create_table(
        'sanctions_cache',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('source', sa.String(50), nullable=False),
        sa.Column('data', postgresql.JSONB, nullable=False),
        sa.Column('expires_at', sa.DateTime, nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
    )
    
    # Create audit_logs table
    op.create_table(
        'audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('user_id', sa.String(255), nullable=True),
        sa.Column('action', sa.String(100), nullable=False),
        sa.Column('resource_type', sa.String(100), nullable=False),
        sa.Column('resource_id', sa.String(255), nullable=True),
        sa.Column('details', postgresql.JSONB, nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.Text, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
    )
    
    # Create indexes
    op.create_index('idx_companies_ruc_hash', 'companies', ['ruc_hash'])
    op.create_index('idx_companies_founder', 'companies', ['is_founder'])
    op.create_index('idx_invites_code', 'invites', ['invite_code'])
    op.create_index('idx_invites_inviter', 'invites', ['inviter_id'])
    op.create_index('idx_public_profiles_slug', 'public_profiles', ['slug'])
    op.create_index('idx_verifications_company', 'verification_requests', ['company_id'])
    op.create_index('idx_audit_logs_company', 'audit_logs', ['company_id'])
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_table('audit_logs')
    op.drop_table('sanctions_cache')
    op.drop_table('webhook_deliveries')
    op.drop_table('webhooks')
    op.drop_table('api_keys')
    op.drop_table('digital_signatures')
    op.drop_table('compliance_checks')
    op.drop_table('comparisons')
    op.drop_table('verification_requests')
    op.drop_table('public_profiles')
    op.drop_table('invites')
    op.drop_table('founder_applications')
    op.drop_table('companies')
    
    # Drop enums
    op.execute('DROP TYPE IF EXISTS plantier')
    op.execute('DROP TYPE IF EXISTS companystatus')
    op.execute('DROP TYPE IF EXISTS applicationstatus')
    op.execute('DROP TYPE IF EXISTS invitestatus')
    op.execute('DROP TYPE IF EXISTS sellostatus')
    op.execute('DROP TYPE IF EXISTS verificationstatus')
    op.execute('DROP TYPE IF EXISTS compliancestatus')
    # ### end Alembic commands ###
