"""Migration: Add Mi Red (Supplier Network) tables

Revision ID: 002_add_network_tables
Revises: 001_initial
Create Date: 2026-04-18 10:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002_add_network_tables'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Create supplier_networks table
    op.create_table(
        'supplier_networks',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('supplier_ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('supplier_ruc_encrypted', sa.LargeBinary, nullable=True),
        sa.Column('supplier_company_name', sa.String(255), nullable=True),
        sa.Column('is_active', sa.Boolean, default=True),
        sa.Column('last_verified_at', sa.DateTime, nullable=True),
        sa.Column('last_snapshot_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('alert_on_score_change', sa.Boolean, default=True),
        sa.Column('alert_on_new_sanction', sa.Boolean, default=True),
        sa.Column('alert_on_debt_increase', sa.Boolean, default=True),
        sa.Column('alert_threshold', sa.Integer, default=10),
        sa.Column('notes', sa.Text, nullable=True),
        sa.Column('tags', postgresql.JSONB, default=list),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
    )
    
    # Create unique constraint for supplier in network
    op.create_unique_constraint(
        'unique_supplier_in_network',
        'supplier_networks',
        ['company_id', 'supplier_ruc_hash']
    )
    
    # Create foreign key to companies
    op.create_foreign_key(
        'fk_supplier_networks_company',
        'supplier_networks',
        'companies',
        ['company_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # Create supplier_alerts table
    op.create_table(
        'supplier_alerts',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('supplier_ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('supplier_company_name', sa.String(255), nullable=False),
        sa.Column('alert_type', sa.String(50), nullable=False),
        sa.Column('previous_score', sa.Integer, nullable=True),
        sa.Column('new_score', sa.Integer, nullable=True),
        sa.Column('previous_risk_level', sa.String(20), nullable=True),
        sa.Column('new_risk_level', sa.String(20), nullable=True),
        sa.Column('change_details', postgresql.JSONB, default=dict),
        sa.Column('is_read', sa.Boolean, default=False),
        sa.Column('read_at', sa.DateTime, nullable=True),
        sa.Column('severity', sa.String(20), default='medium'),
        sa.Column('email_sent', sa.Boolean, default=False),
        sa.Column('email_sent_at', sa.DateTime, nullable=True),
        sa.Column('webhook_sent', sa.Boolean, default=False),
        sa.Column('webhook_sent_at', sa.DateTime, nullable=True),
        sa.Column('deleted_at', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
    )
    
    # Create foreign key to companies
    op.create_foreign_key(
        'fk_supplier_alerts_company',
        'supplier_alerts',
        'companies',
        ['company_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    # Create indexes for alerts
    op.create_index('idx_supplier_alerts_company_unread', 'supplier_alerts', ['company_id', 'is_read'])
    op.create_index('idx_supplier_alerts_created', 'supplier_alerts', ['created_at'])
    
    # Create company_snapshots table
    op.create_table(
        'company_snapshots',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('ruc_hash', sa.String(64), nullable=False, index=True),
        sa.Column('company_name', sa.String(255), nullable=True),
        sa.Column('score', sa.Integer, nullable=True),
        sa.Column('risk_level', sa.String(20), nullable=True),
        sa.Column('sunat_debt', sa.Numeric(15, 2), default=0),
        sa.Column('sunat_tax_status', sa.String(50), nullable=True),
        sa.Column('sunat_contributor_status', sa.String(50), nullable=True),
        sa.Column('osce_sanctions_count', sa.Integer, default=0),
        sa.Column('osce_sanctions_details', postgresql.JSONB, default=list),
        sa.Column('tce_sanctions_count', sa.Integer, default=0),
        sa.Column('tce_sanctions_details', postgresql.JSONB, default=list),
        sa.Column('full_data', postgresql.JSONB, nullable=True),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now()),
        sa.Column('expires_at', sa.DateTime, nullable=True),
        sa.Column('monitoring_company_id', postgresql.UUID(as_uuid=True), nullable=True),
    )
    
    # Create index for snapshots
    op.create_index('idx_snapshots_ruc_created', 'company_snapshots', ['ruc_hash', 'created_at'])
    
    # Create foreign key to companies (optional, for monitoring company)
    op.create_foreign_key(
        'fk_snapshots_monitoring_company',
        'company_snapshots',
        'companies',
        ['monitoring_company_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    # Create foreign key from supplier_networks to company_snapshots
    op.create_foreign_key(
        'fk_supplier_networks_snapshot',
        'supplier_networks',
        'company_snapshots',
        ['last_snapshot_id'],
        ['id'],
        ondelete='SET NULL'
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    
    # Drop foreign keys first
    op.drop_constraint('fk_supplier_networks_snapshot', 'supplier_networks', type_='foreignkey')
    op.drop_constraint('fk_snapshots_monitoring_company', 'company_snapshots', type_='foreignkey')
    op.drop_constraint('fk_supplier_alerts_company', 'supplier_alerts', type_='foreignkey')
    op.drop_constraint('fk_supplier_networks_company', 'supplier_networks', type_='foreignkey')
    
    # Drop indexes
    op.drop_index('idx_snapshots_ruc_created', 'company_snapshots')
    op.drop_index('idx_supplier_alerts_created', 'supplier_alerts')
    op.drop_index('idx_supplier_alerts_company_unread', 'supplier_alerts')
    
    # Drop unique constraints
    op.drop_constraint('unique_supplier_in_network', 'supplier_networks', type_='unique')
    
    # Drop tables
    op.drop_table('company_snapshots')
    op.drop_table('supplier_alerts')
    op.drop_table('supplier_networks')
    
    # ### end Alembic commands ###
